language: java
sudo: required
install: true

addons:
  sonarcloud:
    organization: "compartia-github"
    token: $SONAR_TOKEN
    branches:
      - master
      - plug-sonarcloud

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

env:
- TEST=CI

before_deploy: "mv ./target/$(ls ./target|grep jar) ./target/sonar-kt-advance-plugin-$TRAVIS_TAG.jar"

deploy:
  provider: releases
  skip_cleanup: true

  file: target/sonar-kt-advance-plugin-$TRAVIS_TAG.jar
  api_key:
    secure: Ju0D6+F4PzElfmXgG8GdS8DMv+N3zn2OgS7hNC1vVwjIVd0vQk95uL2QF0cVNaSChxJNFFTKoMepB2HyMMqG7bbpD3C8PudNQTu7DApdc1KouMKjSYAbXmbSLyr/2ParGwe+A5j1LDt74r9BrXZ8LIwokiLOSHoj12qIYmqvexmZiFCsRqDW9JQ6mCl75XG6ovS2Ocmg4rl0JyL3CaOi2ry9J2R1oeQEStyKU0CFjVmkD8ANz2VI8gApo1wi8PrMz7tN762f94cUhtAlCN6susFH/cW3JWY99/4g1mh157PUs9mLejwXWNCTid8E0XojXg8wOsNoXCbT02XEWvRPp0mW7AsUtt4TAy0kkPvKdkQFpsv2QqvaatODz355uUpWWZ9M6LQxCyx54GW1DUKBCOoDkdTuQ+TxTb+UJz2XwQapzQebOuiYHmbEJzMcFxJUHUrH/ypbAtC5ovJ+3chVVv2NfnBXs8SroxqAUp2W/buOM1YzLq2wRqGkGqNlc8CiZQ7wS5KBCILoCLUZe5zwMpMBsJpYHKOyRxMQMFw3Fnm6maluoGZIwbm4zNgP0/JOlcaZ4T9FOMVqTMK/W2aiX+afASTTOZOH/b4nZQDaZoqneuDigx+WeRVZPP44bniWGcpN3DA0XkEfUx3wNz7Tqyoz3RgNtZ8DQHB8IQsyJ7M=
  on:
    tags: true

