language: java
sudo: false
jdk: oraclejdk8
git:
  submodules: false
install: true
script: "./travis.sh"
env:
- TEST=CI
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: target/sonar-kt-advance-plugin-*.jar
  api_key:
    secure: g+9tK1sIkGDh+2IbUs2pg8frA8fWoFSfDgFvHasYoMzvgYmzj9y7E3HIsx/ERoxLvVOUT8KwiLWE7rWGH96yeNcYPtJn1aQTHASfcwsT/UD1r6dEiVnAjinUot+PuWEgBaNkG/Qm+2G0igeTbey+wBD8c9eu4KBgz/SySDG5hrH3rOTliuersZbCjFDewvx0a3ve3LUlS9LssCh60f8c7YkvGoHlRDbJRz53GkXYQ/m/tINn+ObbHTtR5ZNhjpCHdLGWALgJ81OOlbzcmTcG9Ix/4x7NomMQHSNitugYkqwpxG6XPtb9Y7uWHI01UrPrjuYTELkmW2+6ZbJoXNRdKHxOnKCxg51kd2V0KdJbRneU69TPZszdvYGeFPjhXFBzYdIdy60xLSf+M0/kHP9pxkbvsu4W2LrPfOWGJqWAlJTNh7ZoteyqPrqpgV0PnS1G7Z4j8qUuymrmMvwhkmyOY16HuTbPf1YDem+fWE8tQoRrWE24Pva5Q3zs+dVBj1sxrsGQ9DOmEkCrYQ6vT+2n/vNm881BDEdr70ge5KOJ1bnuoDMuBNdmMAN4KNnXIkW0cbL4L43baBBh7HIOxzs+ywDA1PcYiGNtF8F1b0Be39Z4oYv97UNk4L3IHMPkvuEvM8P2vlnX6qZq7TlsmfHiqQgzNbz5aytBFbAyZ2CFqsM=
  file: sonar
  on:
    branch: configuring-travis-builds
