FROM compartia/kt-sonarqube:5.5.6
MAINTAINER Artem Zaborskiy “artem@toptal.com"

RUN apk --update add postgresql-client

COPY wait-for-it.sh $SONARQUBE_HOME/bin
RUN chmod +x $SONARQUBE_HOME/bin/wait-for-it.sh

WORKDIR $SONARQUBE_HOME

#ENV PGPASSWORD="sonar"
CMD ["./bin/wait-for-it.sh", "db", "./bin/run.sh", ""]
